In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
              [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [20]:
a1 = a_centered[:,0]

In [21]:
a2 = a_centered[:,1]

In [22]:
a_centered_sp = np.dot(a1, a2)

In [23]:
a_centered_sp

8.0

In [24]:
n = a.shape[0]
n

5

In [26]:
my_cov = a_centered_sp / (n - 1)
my_cov

2.0

In [27]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])